-- Mnestra v0.1 — real-time event webhook (Fix 6)
--
-- Fix 6 from RAG-MEMORY-IMPROVEMENTS-AND-TERMDECK-STRATEGY.md is a
-- real-time event intake path so TermDeck (or any other client) can
-- POST terminal events — "server started on :8080", "tests failing",
-- "error detected" — and have them land in memory immediately.
--
-- That intake is implemented as an HTTP endpoint inside the Mnestra MCP
-- server process, not as a SQL trigger. This file exists as a placeholder
-- so the migration history is explicit and future database-side changes
-- (e.g. an events queue table for async ingestion) have a home.
--
-- If you want to add a durable event queue later, add it below this line.

-- Example future shape (commented out — not applied):
--
--   create table if not exists memory_events (
--     id         uuid primary key default gen_random_uuid(),
--     project    text not null,
--     source     text not null,
--     event_type text not null,
--     payload    jsonb not null default '{}'::jsonb,
--     processed  boolean not null default false,
--     created_at timestamptz not null default now()
--   );
--
--   create index if not exists memory_events_unprocessed_idx
--     on memory_events(created_at) where processed = false;
